env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "dash.home"

config:
  bookmarks:
    - name: Argo CD
      url: https://argocd.home
    - name: Grafana
      url: https://grafana.home
    - name: Pihole
      url: https://pihole.home
    - name: Longhorn
      url: https://longhorn.home
  widgets:
  - greeting:
      text_size: 2xl
      text: Tomas Homelab
  - openmeteo:
      label: Amsterdam
      latitude: 52.33964
      longitude: 4.96256
      timezone: Europe/Amsterdam
      units: metric
      cache: 5 # Time in minutes to cache API responses, to stay within limits
      format: # optional, Intl.NumberFormat options
        maximumFractionDigits: 1
  - datetime:
      text_size: md
      format:
        dateStyle: long
        hour12: false
  - resources:
      expanded: false
      cpu: true 
      cputemp: true
      memory: true
      refresh: 5000
  - kubernetes:
      cluster:
        # Shows cluster-wide statistics
        show: true
        # Shows the aggregate CPU stats
        cpu: true
        # Shows the aggregate memory stats
        memory: true
        # Shows a custom label
        showLabel: true
        label: "cluster"
      nodes:
        # Shows node-specific statistics
        show: true
        # Shows the CPU for each node
        cpu: true
        # Shows the memory for each node
        memory: true
        # Shows the label, which is always the node name
        showLabel: true
