---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    authKey: AgC2n0lo+llLYurIXqZKu4uNRwaRnGLvZprtCyOctbL1IbBPDG70LtvjdZ3VEzUMp3AEdL1jL4DBUgkXNd7k4FqC0tS/rgOCs8wb/yJ/AXvw+HUmd9QCO6Obd2rO7VF7SgfDKWS7t3L/FsIAeXDorzCrEIEuiwxGSJEGP75kbZ35S2I89KayCKoVKTlaCkTwf9Zek+lVLkmQ115PxDGQ/Tp4yI7etd7jI1A9hzTgm5ctPXOzeAj0M/Jwe4NwU40rL6B6ZbK7JJhMIwhMmz1A2yNACey0SvNnLEckaipJC1RtlurSE3qBW5qft5orzr3A9+3BNTcl7DxyRNAva46B94OmlWNfr2AfadsuVo2qqFigJOWYXUIin1EoYkG67iKzntElBJ60VTVSUGjZlSvACpkQLU5WKdXmT/5RhZ1tWa5vyoHUW+KyXYv7eIPNcNgK/QXBRGGDcJLh6+VdwfE/zmargJtRJDaRGHnWTDd/4ZwwK4xV5X9lf+QjNhx0r2wc2wQWcc+iAkTnLkGFSiF6p86O9wEV0EMlyyX+Lc9oXBdliO8GydHKTj7m6LDQobUXa9k9QpRypimoz/+6Vi1y/YEumWAeq0/CLWJTza7lr3+OOqAmMRMHv1Hcr6rrrfPHzxs1sxKAgc/YA4i8gzJfZ0lwP9jPmXX8EkI7JaSTsU95v94iLAMiDDheILlV+5UHUWqCfSpO/H/1iB+smZpzJZrBDHyVhwW0PbfJiRDfwt4pLbM9+JNJ7fCuK9s30mCQ4sPvOHLVJIde+YqDoja7yw==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
