apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: metallb
            namespace: metallb-system
          - name: traefik-crds
            namespace: traefik
          - name: traefik
            namespace: traefik
          - name: cnpg
            namespace: cnpg-system
          - name: sealed-secrets
            namespace: kube-system
          - name: longhorn
            namespace: longhorn-system
          - name: tailscale-operator
            namespace: tailscale
          - name: envoy-gateway
            namespace: envoy-gateway-system
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: infrastructure
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      source:
        repoURL: https://github.com/tomas-rojo/homelab.git
        targetRevision: HEAD
        path: gitops/infrastructure/{{.name}}
  templatePatch: |
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          {{- if eq .name "cnpg"}}
          - ServerSideApply=true
          {{- end }}
