apiVersion: apps.open-cluster-management.io/v1
kind: ApplicationSet
metadata:
  name: infrastructure
spec:
  generators:
    - clusters:
        clusterNames:
          - "{{ .cluster.name }}"
  template:
    metadata:
      name: "infrastructure-{{ .cluster.name }}"
    spec:
      patch: |
        # Patch configuration for cnpg and envoy-gateway
        apiVersion: apps.open-cluster-management.io/v1
        kind: ApplicationSet
        metadata:
          name: infrastructure
        spec:
          serverSideApply: true
          templatePatch:
            apiVersion: apps.open-cluster-management.io/v1
            kind: ApplicationSet
            metadata:
              name: envoy-gateway
              serverSideApply: true
            # Further configuration...
        
        # The complete configuration should ensure both cnpg and envoy-gateway are included
