apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kopia-secrets
  namespace: immich
spec:
  encryptedData:
    KOPIA_PASSWORD: AgB3IiMweS2bT5k/Hp2nqVmQmeTBu4xX/fAqrml8oTBm/jlMDTDEEbIYqIQL/emnL6GoQ2zNa4NapPhlwk26QbSo/EFLqEaBxxJkEwGAoWlIyf/bi69PbpuyeI0MZPgWSQEPaQXJ2tsciyOjHPo0iULkpbDOVu6/Cqx9KRQ2fpOAKVGaLOW1slsLQJpcsdNA20I26UYmrIN93u271r6uH8HvyTago+y0Ps043d2okEEoStKpd3nCkCT0PFPRbSoKeAVrFbEfkdcx3KhdAI3/4ypdii+6worWcoTwXWt44oGLDraN7uM2zRbHvbcp2U3NHxoNQz113+RzOXY4UrZ1qp3Pk0VHgygvzRii8kOhlY37sld3OEW8lgNlotG4BByLExeKUaGuqdduPIDU2rjib9QZMkFepFZZnTGJcx/THjoEnUnkctiFSOB7uKZ2rQdS/0u5NJcJ9hVGg32X+p9/XttBwsSptVMQSDZsOaMPx2VSds2ZFyNSxfkxO6tiIld0GkZtG/TYTdp7tBPfNVuMsjuT+tHHCbIVnCx0HmtzkTCyxsE/f8xzjiJpq7qMQ0sW3/yjUiAc9TVz75XhZyGk8KobulkHRQTZ7pNhHpmIVJ/T8yzdcSchokdieWKTp1L659Ds/Incgqq0wcO+4Fy+oGWq28AFxybuqOYj/bN+XQUqbqKeXOsBg5aCnQwchMkoGqA3kalulB5+PkYxtrg/ew5rqg==
    USER: AgCa/xI2gZcUG9Z/jDNhliB7L4QXKowJgI4TMCNLBn0CqMvc4UA+1AfrRbUDIBGgqrILieT0AxU6XZER3fhvnGkN8jo0JpxAC3BYy+TUxk7mAB5jhIeiqkGn+a/S7GoVJJYD/Ouo8vuARx/AyIOKPtRdpNU+unaUvDiFaFJWFOmvrT5xjB6W5BxNvy10l8KK7Do3vY4R5hAeSZAV/U9f7StRzZtsaMdFObHf5kq9/mIlxXVlg+pUpqj+5iEd75Lpd12EycnjTBShFyiEW8NTLuUnmsnehehU9b+PzCCPtrkz4pygf/9MKyRxoOIaCGnKij1HK8YAJaupPHJGhicu4UqgSasv3SFthFhDgW2/vyiOVs6ztgTUN7T3ckIhIzaG5affwl+Gvv8GqglcT4jhZw57Sm/RPTvQwHmZtvbDhRvkxvJ4pg341cycuEESIYS+r7CnASLfiHjviEn1OURip+ipJr1j2sUEGuOoMFj0MU4VTJoaLfGJlyOjowzQr92Gt0cNV/qk0KOEu4iNXcOdWrjh7SHZoq/VlWXnKSIGUSUc4KFInNw+LqjXTjYpYG0K6hw4d+JpOJBhSQ1QwQA5Wuqmw5lgTYaMSIlF1Bx9+TIx0kHlc56w6B1vkX6miqHknqMIw6wG7I4BJ67xcV1X3yNpRFI7IUZEvBiDJ5YqTFJLjG8GOHY3zr1f/wHQcG58WAwuMCxu2A==
  template:
    metadata:
      name: kopia-secrets
      namespace: immich
    type: Opaque
