---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kopia-secrets
  namespace: immich
spec:
  encryptedData:
    KOPIA_PASSWORD: AgBHVDWtQ+Wua87ag2McbWoez4T6CdaLL2VxCuyVLLPJ/oA2/KhZOeUBQF8yalf1rqxLakBS9gPZHPsTDr62YW5tVPCMFaBSuLpOq8a+GgdKDUawW4RK7UP1rpgZwR38jIXi3fW+/fkr7blHXFeftW7qfHJ6+Y/FwmPgijdJ7aiDgWoUeJwGSdlz1hjoBYpw1/A3r8l2zv6HWadtku2QdrPsL1JFT6vqBh35DB6fuxpy0ojUJer5exqR8jSnA5wZaKbbgoREceV+w9MOjHAqhdTtfy4IPPDbBeBDWqQMxA2mBDUto/OGUjQv5XrcHJ43ecPleJrNvncWIHD5JPn82ipGA+MvywM64h2ZQ0K3uHPgsEnRb+0cnPU8aPgUAoqNpv3TMn7/kt7LLuW6CbvbXTFz1AKzHhLgh+EOJw1uCrtp+HyNgalnwGinqi8JuqBaIrXF6Uh6rIKZFjcDVuoEvvYv/6LtF/JxkZLikXHo6LgwsS7Za5rhsuiQpbYL0QddsSPTFHTXdtpJgk0iqhCS9vXVnpTOABTi+RXLsd0sltREdCBWwMc2xaDYQCTODvV3wSl7c1UJtKCC9grg4zNZ1PuChXOe3blaKmYxR0UuxPnN0nMsLiOnG7Kf3V0k8LRAaqXsilwBTFShVfVTechWlsK5NoJSx6KWwzY67NXorWS4h9jvfIA+spYcV+88mnFFCTntdfM+299PnYu+MSrjbNN+Tg==
    USER: AgA/3qSP9vWLb26/j8LpIvoRBWF6ion2U90txFV5a4y6qgnQOYfDlk1jIzRdE/TP194fPlokoWUNPgaFVuPREkYSvcTaTXhGNHJ+rJ4Duk1Zqr49toF7KifccfqUmKwTlZIZ1QYfAhn0VY0TbA4957n9T5Xdl0TWg3EKK0kbOiKxJza4lst5PPZxadquJeX9+7VG5V0AsNqdC9aq3LhK/YOPBfQ63DXZkWwdnZaIQtaCzfAuSUw2/8AFYhgVt2sqHTMno3GPaSL/MaYravgztDG/kk/sDrVHI6dBZkjkH4GwPS7R0hVfE4Whj333o3jyeNIWKL/m0OmX8BjSJoVFbBcy+Iwgllmcwfhtqk+8SzjgAxLJzYF8GTTNCmr94CY3QpjohMgWHFuLYgRplsQ+NNW4F848i7/4e+uRaHZD4XIBXQ7zu/xNQoBUHmDgvfUAwmsAxiQIBD+MnsEGYPLynceSzCmvYbmJERrcNTGOpAU1q/j0DEyuaDqjitpAhQpW59IetsS7uILtkj4O9qguolFmHx3Vcnbiz3tkt02S2a4tzodHCtrrNC9859i8RH+/eZquhGKyio89k664ME/xGWW/K9bIVx2gqjSNPJgHWCE8asGqY/q5lRSoxYP0Rtq+K6B9MlZU1BHqU28Ow3w9XBOP1XKMez8kcyc7MSN/Cw2nl8A1RevNHWO0VQllsox3Dd+8cvhT8A==
  template:
    metadata:
      name: kopia-secrets
      namespace: immich
    type: Opaque
