---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kopia-secrets
  namespace: immich
spec:
  encryptedData:
    KOPIA_PASSWORD: AgA1hy1sxBJ4t6dSuvFfiiHRI/mRd52YEF3bsMVSwGMMQ+9ktjw+2fyiYVTCTUlgsBAbebB9MqQjs5vd8WDpGehVAHvly9BihKFpsRCI7Zm/DsHBS8ALZL7wyKFL4FvQCVOXRK86E56Ko28wF2Yypo6mwF2bBMjwffQglOxFB3eQ08pnNKiCrChdq6EObb+52oq816tPXph5oqaETkV3X0u4LGgG55tExD0o6fYnrW90Q/H33wQuWuKKG7MVsIe69srB8EGda3LyF9YjUm0cz+6TlFoAEfOAhATgkIOUq9UFMB0Yc3t71a4MWHInOjufZfyppSzmxAiYpUHWKUqYesmpPJq+lyZHklQtayzjOJ7CzOXffk3GdIkUwRLdlyXtn7iZGkDqMbTOfxcgkjmBGNLRrr9om718SvKHjE2/yXpJrnLOeJ5FSXDuYfqLdA93dcnBPPTch5vrbpG0KBPdyNJigZMa6AyAoZFGKJavWFJXy3lQ4ZZXbjW22skJM4EqTmCW+9A6zHmUwStJBkNnXtobsiWtcEwonI5MRG+my86I9dd+JOVwaninV62cb2bOTnIanp3hzhLzUcwbGX05Ur3jM1PgUtykd8W/mEbRnbP4fzswabD3TIAv3YoHPPO89sxRSoqdFxr8aYMq6bNYA2/KiRYcxPiDoV0rG82rxbcMyaZowC8GxNiomPJoBcgWj81xMblOFC7EbEelnFQ564jglw==
    USER: AgCFi0D0Dc+xvEzfSQ/QdKjky3CUhPB4POxG4vwgoDZEMTm+JXCOtCvxFqixVsaDbz0lEnu07zMQ4/IPO2Hk3DScw8er2mQ51koe+x9xN9t9dX3gYuZs9nUybxU5K7DfNDtODkkmgbhLqlz92pVZf/jRyINCudaRbWDDM1DjVafvQ2b60ubewICskIbXwSD4H79Qy2qC/aPSdN9FiQ3sMV+kdWLHo8shZzBcBCJvHvOPD/H39WXTY1Tnv9fTtE2WbFcXGbfeeVqB39B2hpXcXQvU0lsseIsavjRQ/UluN0PrDT+QywestG1gAF0sfByabw1KKKI303o4BwDDYMgB2cC2z4Ew3ug+0CO7TJOuHEudV5QvCLPXPaHSIyScrWCBThvVAF8j0nXLzsmqCPf2+aBOmoZ7sWtxEPrvhZbycFdpXX2kgbjKV3kEkf4z1r4dxrGmRC3sbAzLFJX/annnhdHCp0oAETYXxjCaFt51UMrJetbeBiGdIyovA/nn8AM4/9luXv0DulcVWxcTOIJiLjg3xv4ZlOuFqMjP8Uj3vLy8uP/yzZCqzAPzYOs0IKkOHcFV86IQc2glXAjqLPDRH4g+cEiUZpQxR25OFYwML0zjMZwJlHIycHK6K7JeeSSVvdCFjt293GZxb9N2F8FdcB+jJ+gjXErVoVTF3UZ3kQyrgLaz78S/jpIp3efbc1mRlR3L+DH56Q==
  template:
    metadata:
      name: kopia-secrets
      namespace: immich
    type: Opaque
