---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kopia-secrets
  namespace: immich
spec:
  encryptedData:
    KOPIA_PASSWORD: AgCqiGU7C98DjIG4uOS8GnyIZRPmPxixfE+4bFg8lDeC582JEibfnEqhlqphJ2C8BPDsTaKH/9zZjwY5VjQR6ugVT6+jGF7PUMvNxbVg4Ww1cFdlmqQwN5A5X2MnLULPKLoFf6qEeWMEz4CTukeIKisuiz/+gtPOogCZFdiypRuYWMU6tD3IY6ybA97FFnSRebCFeZSzWjzCV82dtWAUd+Kv7Hdpb21RN/ISrwXnw9SRknVHGYjJACJR9dQnjoy/o9/Wj9eWEohKFlrC4fU/ELeLWrXn6wiipGPqj23jeVNy3fWASLH9me3uK+WRJ6tVZqLNBpFtKK+LZnxu78eyDW4ggEuaQWRFIcQRn4UrcJ+U+Df1BB68msykhJIgEYgg2FwOPrhvDmeMnjykqPND8aC6pVf4abv8U+SXTzhVWBwnYrLjo3WjS0ZgHuDWeYy79Pw2z6wCTwdGLpi8CB1FM5EkN99ik5RWvSOEbgUneMq6M4jJG0Z8g60z/rdJwveYXpqpJQXayQBPzymK4A9HHNC79JFBnvJIbTvWlp1gKgNC51lKkZIy8hErBv33UrfVBf3lRATD78ofP1CdRpOu2fLNzYVZ7MgqobpThDjFTDQGyl41Xm0ETsDue8rnujM4i6c1bXhmYJTL2TiMl84q9hYjdxawA4X+s+j0jTAKTRlSINL1+Am3yPAVxYzCnKpie3jg4l1Mmg==
    USER: AgB+EuM0c9zed2uLIYwa6ABmgSA+SkyhQcxChiYlt7a3JTaea8mx/6u3+nGnF15oOu03CWwYDxNvl8geinJVwrcZsfAyJnMoOnAxhPHwfzX3ldIzTV426F6zZaAmuyh8yqeHoH3Z/NHtLHx6gcsRif8DbhqOlpmsIydUL+s9JbxiXVV9Z7ZsKqnDBqli0HmnRehYj2JjJXKv3Fd1X3RCFCmCPgD8GrdJUdOIR3xAoTWRaULtDVuxXstPzDi6nlldL1PL7JmGggSUAd8rbGcOGtZDdjSY9/Q2G7V+sYM6ddyJTK4OH4XSAVvIQHKq6s38uraqDrn24/uSlQhDDCA+LZTeoi+fJpNm+oVRZwC0TCBspJIGj11V1B/11xvzK15R0WqV67DnfSj8vcsVDYq+TLGW28WcPkuLCpBfWG669y3r0R2nBPpPf59I0M4f72ZvldinbIr4JXBDycdZgmzZW/VvxHEcm26p0m4ispygOuWI2aQHrK8DjVBxSy8SZ/NpPz0E+RXCxzho/idH8ZlXx9MDvKd43YOr3T0Jbekl05S9zkqeAU9qXPAey3DyRE7YEJhay8c507vYqomwxrYQMJPbL3o3H0snhKMXnDPsrYMF2Iixvnc3wv9f3a+15r2pU8DYJ9uJ5ibb9uOHdoa8FqqTNvqA5I2aD3iuWJsXUgFHV0bqpnuAIZ1Or9unI7Ja0sb3inobPA==
  template:
    metadata:
      name: kopia-secrets
      namespace: immich
    type: Opaque
