apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources: []

helmCharts:
  - name: kopia
    version: 28.4.0
    repo: "oci://oci.trueforge.org/truecharts"
    releaseName: kopia
    valuesFile: values.yaml
  