apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-postgres-user
  namespace: immich
spec:
  encryptedData:
    password: AgC1V8Ys0YAmN6qUFIV5UVBoXETXeigteCFKgS7uGxYRuOSV4rOCM82OS81LXsIJ+51Ei+QBVnZ+9kXOtG+M1N6J1h6/GJ24oAG11WIkc8ho7iIh9c2VkNScFwMOh5Oc7s0w/0BpFvx1/jQ5NFNDGKeXnCwHJIyTRd9b7cw8OYpS3iuH+Jt9QXsikgoO4VmsluD+NAg7Bj3Sf3vwnr7WRNt5JmHEYCA0/0azJI1c2e2tvH2m4BS63rMGjiMdCdm6yD/NWLjGv7ZQsapGMMiDaXCKxH/9z56IXFvt0DZYjMF2nk+dS1Kl5yqLB5XO6D0RE49Vc0kpaqY7EcwxnNNCtx9uDQzYoEH/cLRcNFXYSrVEBW2jgwofDz3QQ1IxF7VzYYUs/IFmreLG862vshOWqlP3TgwGcsJYuX/2stNAdE1MX/Xg33cyX90gaK6tChcAFfDNiSGq5umhAN9nAssiNcMFX5F/zA9XHYJz4jp8f7Ki9lvsR38N6d8nbh00q7UxLJ1itRfkaEhliPSI2Q7N52MPzUlnGq/uVa0oeT732ij1QLo5UFT0ur8jxdO3gKMNZwPVdjNYhU7aPYxq9WAFZIkmjvDb94nyi/up7EIH9eHk8geKObx4dX0MAOgPOwm1d1SuvQn6M0ycICiyJPGuEQd2fj8DsSeddowdGba73YH/nVHWXBq0pczGKZOXNz3mCCflsnxFOz8=
    username: AgAJVaDdmg7K8dQ5Wm3AdgrCKXpGeDSd3XezgiP8yTkBXDMERIpqSVDxSUPc1uUZ8xS0G5YBYLJVeXP9rt70PVl4WLDs6pPGDUErGuF0hD7G8W74ua95KaW8eP0Amo6NreSYoMXpd6OKdnT6g4yMav9tTKE0h4T+AYtItY3qVLtlANu40GPrGvqMU+af8oVphnLdaQxop9c0FNMmu0cYThOFrOYwaVDTy0SDblEnMZvk0ZTWkEWZUtYnpLaCZr4tCSnM3+T951F13Q+AQMOv3Pb1/Zn49s6czqNXUGX7TekOQ+CTBN7RmqwUcvVKKUqsWrSNW8l6egAKf/iLvOkuBzyZVStA1vjPK4Xs2xes+D2+uj1jM96p2rEdB3/nAEaKeIYrwFMmgeHOjm7/OzMnPHNdP1fvUj4p9r670etaeXj39ff9lR2Wo1hOyEYRl62ebKnkS17Q9lqqTMq9/F/3PvMBnqdztXBu8ENByiqK+3Fq3r1yFr6SF/hya8MvbyrXAVsUzSI09LNw1rCPZaIZsz3Xih0AoKL/aLSKhXi5bIzvfenfotmIH/a2eFmEPU8pOBC+kHb50Z2z3Yk/A0/HqDon5SnWqNu+0+cYgBvCRsryAcaAzrJ7CidZkP6568QCCb9BTfJyfhROOR0xOIbTVKzjbqw1pCk3U/xfhr1Z0FSQkUAJzvnb8yh7bOHvzrksfp2vj7SkoLM=
  template:
    metadata:
      creationTimestamp: null
      name: immich-postgres-user
      namespace: immich
    type: Opaque
