---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBHIBkgUGkLm7Y0sD13jvgays3PunXvSqsZ999YBN5h5hCP/MVD9Fba4qk8sHLjIONByX46I12+qoTw8M6ikJRPZxD+OFYMmalnrAb7dNVfIwTYCK7qXxlztZ28aoRvitzIXWLq9e1qjQFAqnUr3Boo6IqGVlMOu0TSvFvnPTeQrxI+ge7/AxCifzWD2YY5t+K4Rj3nPe5JBpVneJod8QUcoBZvVSE4jkDsyOPu2rtLHphvt17biB0a0qfeMG88Trl0rey3pRtG0tade+vWCGC1oe1YKHJ2BFVf/24J+kKNCQu+v7fanQUrPnz4wVUKnJTc5SbVTsdyF2HlMXK4+vBPXkbuRUvS+ohMyyRuAck3RdDWHTuaRf24K+c++8BqssfTnw0Tfi4ur0FZY8yUTdVHaJhU/SKVMuvRDXhXYyHNegNUe1Lxy35cKGb6ftAFc+GXTz9cT1uXTRMWAmb0I12EEba4VZsdJvik03+FXz2pA3V+OnYHxAaldY2JBGjHXezxHMev0Xlq2W9AjUHvrM63OPN7C+W//ozfSmVhhWPfHjcndDq+TNqBNLqQ3VSGaVZnQ7DB2ojvkbk7qYE/E0jsmuhZArAcdvegT6rpDbLj6zwfOnKuJU2BHcZS5jihZ6QbQbxAHr+TWDtljG6tDNjYhf+7awIGTDPNFs+CeogKqNjTeRBvpkMNdHIpU+Qst8RsVnZKqnr7QQ==
    admin-user: AgAVnoVMphweh8UBXVFIuY/2pzkBJCoINXBcEgr3WhbiTrfRLDh6SbNGv6lTXzAVqTOf8C7LVL3oFN+dseewoRttq9IoDhPVteJJOiWiNXsNdNXF5E5Ee+X4BF4aNKZt+8g+JX9XgY5yO6Mep7nr0IqFTn/mmtuXXo9r6n7zWhSQPjSTJF9sDTXEciOSiO4Sy4FnSB8ttFnKXieQBiL5kP9sU/bxTwRicVIEkVWGRY3zVJ68HfFRrVJFiPFk3+TLFf2UFB3I7EtWkfJa2vpHNzHCfjXz3HVbKqXUwKbI6ayV9Nq/6r9f1YUpfZIc01/TfBQ+HJ0vl1rSIH7x44uQ5F0CfobR91SX5qR9pU/iGONvBSx7AfGcNtqqGjJGcDeQ8QN7xye7i68dfWVApyxQKZrauxp2bLlsTi6TdLMWeuVF2kq4ATFgWaRDE2EZG5XfoM/QSLyb/Twu8Q4IfhDMzbANyDAkxubTMAbs3C1q40rDeswi8+k1YN436jeYasrxfPrs7n2wDcAWvz4kgqEXCipRvXJzRQehcMN51s90Lv25fOtHoTvDWQ/aRX/A3fdo3b6K/XepramFc5c+Vx2GXe41OUy8FX7Bjvv9AqJQ2vBzManU147y91xCosDEM7TMlHfIKeO6mShAdZx/mNKeIaNdLPOchKA4Smr0tGjxZBjqvlqC6YvdnWaWri+uz+T2El4ZgdgVHA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
