---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB6pj2m+SO6P4ibahe71ZX9mX7dc62xWG0dppRSzoFdUmz+gQf8KSM735pMj8+Vs0PgbX+Q9vTURZurRtZqCQLmNnFEWiVnnIlT8cDgltUUoiwDavTYM61nPExwxDSICxy6pwpawvpIaQ46QofpCnAt2FoLiEo3Kfa18kGzsRaKP89WQsa2a1/Za4SgPIW10aZiDdIWG6mkyQZS1Hd+fwr7OhGu62zGjm7rvBADQWKhOwpyNUmT73VrGpSuxnMSkHsrKK6D7w+Yja6t8BjsAXaxdSt3Yui9YxVukPNynOR+f2PuQDpUM4yUQ/ltgGVqEcn4S5CjF5FH+rwqK2eXV/M/NCKoNifBB79fJ8Gco9rRpGkoJPdWEDS+BzJ0mz8mbYmwmahXh4IoUyLHwtdBnMkpqoPaTOvaTVv9zAcN7NN7LKGABY4RtsIAsR8vGtvP6imVzZpBEaqa15dVb2+kL2iqVi/rpoBumNmlk8K6NyaLj2cv4cqaF8EES0XUwrDeO0zkYuf6gGfRAEueXTBgaIcmScYRXNTN9E/xTMCMM/rB2GYMi4WNPs/eT9S73TrlaQZ5Zk0PbJOORES0QVs4MKWj3xlZR0vPt9HJR99j2dfTIjDOllzCW0gsbRip0hCeyGdXaPhQ5fA/dG0UZghJYty3Dogkw7TIqb/Lju8H1iAgHhJOrEvahuImYlfV69DFCw3s0/ub5WnFdw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
