prometheus:
  enabled: true

alertmanager:
  enabled: true

prometheusOperator:
  enabled: true

crds:
  enabled: true
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/component: operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"

waitForNodes: true